LOG_ENTRY_CHANGES = 0
LOG_HIERARCHICAL_VIEW_UPDATES = 1
LOG_CHOOSEN_COLOR = 2
LOG_PROFILING = 3
LOG_UNDO_ACTION = 4
LOG_INVALID_FILE = 5
LOG_FATAL_ERROR = 6
LOG_DATA_CHECKER_STATISTICS = 7

DISABLED_CATEGORYS = ()

def log(message, category):
    if category not in DISABLED_CATEGORYS:
        print(f"INFO: {message}")